Hw04 lru cache
alexandr-kaa/otus_golang_hw pull request #4
Opened 2020-09-28 21:16 UTC by alexandr-kaa

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-30 05:48 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/81612/8087/

Здравствуйте!
1) Вы мне не выдали колаборатора, так что не могу ставить чекбоксы, а также перезапускать джобы в трависе (это помогает от покраснения)
2) Хорошая работа, но в кэше замудрено, нужно переделать

Спасибо, предварительно
5 / 10

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	Value interface{}
стоит ли экспортировать здесь что-то кроме Value?

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +		return -1
return 0?

все-таки странно, что длина у списка может быть отрицательной

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	if plist == nil {
не вижу смысла в таких проверках, если вы не реализовываете lazy-список

предлагаю на nil plist инициализировать его и продолжать свою работу

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	*item = listItem{Prev: plist.end, Next: nil, Value: v}
```
item := &listItem{Prev: plist.end, Next: nil, Value: v}
```

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +func (plist *list) Remove(pointer *listItem) {
`pointer` - очень общее название

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +func Check(l List, r []int) bool {
проверка чего?

может быть `Compare`?

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	return count == l.Len()-1
какой эта проверка несёт смысл и чем отличается от 111 строчки?

здесь не должно быть просто `return true?

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	for key := range cache.items {
1) items забыли очистить
2) проще здесь сделать переинициализацию аналогичную конструктору

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	count int
этот счётчик не нужен

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +func (cache *lruCache) checkAndDelete(keyexternal Key) {
что-то вы намудрили

1) у вас сейчас операции кэша из O(1) превратились в O(n*logn)
2) у вас сама очередь и является гарантом частоты использования - наименее используемый элемент находится позади очереди, так как при любом "касании" ключа вы выполняете MoveToFront для элемента, с ним связанного

перечитайте, пожалуйста, ещё раз алгоритм в ТЗ

2020-09-30 05:48 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +		if cacheItemvalue, okTransform := valueMap.Value.(cacheItem); okTransform {
а если не okTransform? :)

вы вернули nil, но элемент в очереди подвинули

в данных случаях позволительно пропускать ошибку или кидать панику - так как это прямая ошибка реализациии

2020-10-03 07:02 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +		return -1
Это индикатор невалидного указателя. 
разные состояния. Очередь создана, но пустая - 0. Очереди нет как объекта -1

2020-10-03 07:08 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +	Value interface{}
первоначально и не планировал, но в тестах были поля Next и Prev. И к ним шло обращение, поэтому сделал так, как используется в первоначальных тестах

2020-10-03 07:10 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +	if plist == nil {
Нам на лекции говорили про объяснение указателей и вызовов методов по указателю, что должна быть обязательно проверка на nil

2020-10-03 07:11 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +	if plist == nil {
Имеется в виду создать указатель в таком случае? Обязательно исправлю в этом моменте

2020-10-03 07:14 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +	*item = listItem{Prev: plist.end, Next: nil, Value: v}
Здесь я еще не совсем понимаю время жизни объектов в го. так как я написал - создание объекта и возвращение указателя, потом присвоение ему. 
Опасался, что после выхода из функции listItem уничтожится и указатель будет невалидным

2020-10-03 09:27 UTC, Antonboom commented on hw04_lru_cache/list.go
> +		return -1
просто непонятно, кто будет пользоваться такими состояниями и знать о них (тогда уж выносить в константы).

т.е. предположим я где-то пишу `(*list)(nil).Len()` и логичнее получить 0 :)

2020-10-03 09:28 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	if plist == nil {
да-с

про обязательную проверку на nil в первый раз слышу, вы наверное как раз путаете с `default value is useful`. т.е. я могу заиспользовать `nil` объект и он будет работать (в данном случае не будет)

2020-10-04 05:55 UTC, Antonboom approved these changes
Здравствуйте!

Часть моих комментариев вы пропустили, но в целом гораздо лучше.
Принято
8 / 10

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/list.go
> +		return -1
актуально))

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/list.go
> +		plist = &list{}
```new(plist)```

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/list.go
> +	return count == l.Len()
здесь тоже был мой комментарий, актуально

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/go.mod
> +	github.com/golang/mock v1.4.4
крутяк

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	mapData := make(map[Key]*listItem)
преаллокация

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +func NewCacheExistingList(cap int, inlist List) Cache {
такое можно делать и одной конструкцией с помощью паттерна функциональных опций или использования `...`

например
```golang
func NewCache(capa int, ...intList List) Cache {
     if (inList) != 0 {
         ...
     }
     return &lruCache{capacity: capa, queue: NewList(), items: make(map[Key]*listItem)}
}
```

опции:
```golang
NewCache(cap, WithList(&lst))
```

почитайте на досуге, если интересно

2020-10-04 05:55 UTC, Antonboom commented on hw04_lru_cache/cache.go
> +	for key := range cache.items {
актуально

2020-10-04 07:24 UTC, alexandr-kaa commented on hw04_lru_cache/list.go
> +	return count == l.Len()
Здесь не согласен - если внутри списка ошибка - не все указатели через next прописались, тогда он насчитает не все переходы и выдаст результат false. Если вернуть true, то будет считаться что длины списка и слайса со всеми переходами соответственно совпадают, что при такой ошибке не так

2020-10-04 08:30 UTC, alexandr-kaa commented on hw04_lru_cache/cache.go
> +func NewCacheExistingList(cap int, inlist List) Cache {
Сделал, добавил тест

2020-10-04 08:50 UTC, alexandr-kaa commented
> 
>     1. Вы мне не выдали колаборатора, так что не могу ставить чекбоксы, а также перезапускать джобы в трависе (это помог

Здравствуйте, Антон. Я добавлял Вас в список колабораторов. Подскажите, пожалуйста, как поправить настройки? Я похоже что-то пропустил

2020-10-04 10:51 UTC, Antonboom approved these changes
Про доступ - мб я пропустил инвайт? В целом непринципиально, но можете еще раз пригласить в репу :)

2020-10-04 13:32 UTC, Antonboom approved these changes
10 / 10

2020-10-05 19:04 UTC, Antonboom commented
Вам нужно было нажать "Merge" вместо "Close"

2020-10-20 05:31 UTC, Antonboom approved these changes

2020-11-08 19:29 UTC, merged