GOLANG-6 6 домашняя работа
alexandr-kaa/otus_golang_hw pull request #7
Opened 2020-10-25 19:27 UTC by alexandr-kaa

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-28 17:39 UTC, kulti requested changes
В решение есть несколько ошибок. Предлагаю их поправить.

2020-10-28 17:39 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				}
Зачем эти пустые скобочки? Выглядят, как две лишние строчки. И, на мой вкус, довольно некрасиво :)

2020-10-28 17:39 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		}
В цикле два селекта с default. Это означает, что селект будет почти всегда выбирать default и просто так тратить время CPU. Правильно тут во втором селекте тоже ждать done (без default).

2020-10-28 17:39 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		return nil
Довольно опасная практика возвращать nil-канал. Чтение из такого канала зависнет навсегда. Зачастую, лучше вернуть закрытый канал.

В данном случае, проверка in на nil куда больше имеет смысл в ExecutePipeline. В ExecutePipeline это внешний параметр, он может быть каким угодно. В Worker'e же это внутренняя кухня, тут можно ожидать, что nil никогда не придет.

2020-10-28 17:39 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				return
Это приведет к выходу из горутины, которая запущена на 29 строке. Горутины внутри стейджей зависнут навсегда.

2020-10-28 17:39 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +			innerChannel = worker.execStage()
Не понял задумку с воркером. Почему бы здесь просто не вызывать `stage(innerChannel)`? Код будет проще и понятнее.

2020-11-01 18:21 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline.go
> +				}
Исправил

2020-11-01 18:22 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline.go
> +		}
Исправил

2020-11-01 18:22 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline.go
> +		return nil
Понял. Брал как пример из теста что-то похожее

2020-11-01 18:24 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline.go
> +				return
Здесь не уточняется в задании, что должно быть с горутинами в стейджах. проблема понятна, посчитал, что закрытие входного канала, завершит горутину корректно? Переделал этот момент в воркере

2020-11-01 18:25 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline.go
> +			innerChannel = worker.execStage()
Это такой ООП. Обернул стейдж в воркер, как оказалось не зря - теперь после переделки воркер управляет входным потоком для стейджа

2020-11-01 18:25 UTC, alexandr-kaa commented
Переделал по замечаниям

2020-11-02 17:46 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				return
Это называется утечка горутины. Она никому не нужна и никогда не завершается. Если она происходит в методе, которые постоянно запускают, то таких зомби-горутин быстро накопятся и начнут влиять на работу приложения (отжирать память и время CPU).

Лучше так не делать. Иногда при выходе из приложения или в тестах на это забивают. Но, на моей памяти, это даже, казалось бы безобидная утечка горутин в тестах приводила к проблемам с тестами под рейсом :)

2020-11-02 18:00 UTC, kulti requested changes
В решение есть еще одна ошибка. Предлагаю поправить.

2020-11-03 08:29 UTC, alexandr-kaa commented
Переделал по-максимуму

2020-11-03 08:30 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("TestWorkerDummy", func(t *testing.T) {
теперь этого нет

2020-11-03 08:31 UTC, alexandr-kaa commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("TestWorkerDummy", func(t *testing.T) {
Добавил обратный тест

2020-11-04 11:54 UTC, kulti requested changes
Можно было не переделывать. ООП подход тоже имеет право на жизнь.

С другой стороны вы можете сравнить как было и как стало. На мой взгляд код сейчас лаконичнее.

В решение есть одна ошибка. Предлагаю ее поправить.

2020-11-04 11:54 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +			for s := range stage(in) {
Если в in ничего не пишут и не закрывают, но закрывают done, то выполнение не прервется. Предлагаю добавить на это тест и поправить.

2020-11-04 11:54 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("Check it!", func(t *testing.T) {
Проверить на разном наборе стейджей — хорошая идея.

Хорошо бы еще добавить тест на какие-нибудь пограничные условия. На пример на тот баг, что сейчас есть в коде (описано в другом дискашене).

2020-11-08 18:04 UTC, alexandr-kaa commented
Исправил последние замечания

2020-11-09 14:01 UTC, kulti requested changes
Александр, добрый день.

После фикса вернулась старая проблема. Либо вы торопитесь, либо не до конца понимаете, как работают горутины и каналы. Если чувствуете, что дело именно во втором, то вы всегда можете спросить о непонятных моментах меня или другого преподавателя в слаке в личке.

2020-11-09 17:40 UTC, alexandr-kaa commented
Поправил, чтобы не было зависания горутины. Теперь чтение из канала находится внутри select

2020-11-10 07:58 UTC, kulti approved these changes
Теперь все корректно. Здорово, что не бросили и доразобрались со всеми нюансами.

ДЗ принято - 10/10.

2020-11-21 10:26 UTC, merged